language: r
cache: packages
warnings_are_errors: false

before_install:
  - sudo apt-get install libnetcdf-dev
  - sudo apt-get install netcdf-bin
  - sudo apt-get install libudunits2-dev
  - sudo apt-get install libgdal-dev
  - sudo apt-get install libgeos-dev 
<<<<<<< HEAD
  - sudo apt-get install libproj-dev
=======
  - sudo apt-get install libproj-dev
>>>>>>> dev
