---
title: "Example for older versions of ClimateExtract"
author: "Reto Schmucki (UKCEH)"
date: "07 April 2021"
output:
  word_document: default
  pdf_document: default
subtitle: "pre Wild-Rose release 07-04-2012"
---
---------
In this tutorial refers to the method used in climateExtract before April 2021. While the workflow presented below is still working, it is not optimized and more flexible and optimized approaches have been implemented in climateExtract and should be preferred. Nevertheless, the original method will be kept for backward compatibility.

### Pre Wild-Rose!

You can get your climate data from the web repository https://surfobs.climate.copernicus.eu/dataaccess/access_eobs.php\#datafiles and decompress the data to extract the `.nc` file.

Or you can use the function `extract_nc_value()` to download the Data directly by setting the parameter local_file to FALSE and adding the details of the Data you want to be extracted.

**1.** To extract climate values for a specific time period, use the function `extract_nc_value()`. By default, this function will open an interactive window asking you to select a local `.nc` file from which you want the data to extract; you need to specify the first and the last years of the period you are interested.

```R
library(climateExtract)
climate_data <- extract_nc_value(first_year = 2012,
                                 last_year = 2015)
```

**2.** If you don't have a local .nc file, you can ask the function to download the desired Data directly from the web repository. To reduce the size of the data to download and manipulate, you can select a specific period available as "chunks" of 15 years (see help(etract_nc_value)).

```R
climate_data <- extract_nc_value(first_year = 2012, 
                                 last_year = 2015,
                                 local_file = FALSE,
                                 file_path = NULL, 
                                 sml_chunk = NULL,
                                 clim_variable = 'precipitation',
                                 statistic = "mean",
                                 grid_size = 0.25)
```

*where clim_variable set to:* \* "mean temp" extract the daily mean temperature \* "mim temp" extract the daily minimum temperature \* "max temp extract the daily maximum temperature \*"precipitation\" extract the daily precipitation

*where grid_size set to:* \* 0.25 extract a grid with a 0.25-degree resolution \* 0.10 extract a grid with a 0.10-degree resolution

**3.** To compute summary value of the daily values, use the function `temporal_mean()` for temperature or `temporal_sum()` for precipitation . This function computes the mean for a specified period, monthly or annual or for a specified window, computing a rolling average over a specific number of days. **NOTE** This function use the data extracted with the function `extract_nc_value`.

```R
annual_mean <- temporal_mean(climate_data,"annual")
monthly_sum <- temporal_sum(climate_data,"monthly")
```

**4.** To extract the weather data for a set of specific locations (points), use the function `point_grid_extract()`. With this function, you can extract either the original or the summary values corresponding to the points, depending on the data object provided in the first argument. The second argument is a `data.frame` with the coordinates of the points in a degree decimal format and using the EPSG projection 4326 - **wgs 84**

```R
    point_coord <- data.frame(site_id=c("site1","site2","site3","site4","site5"), longitude=c(28.620000,6.401499,4.359062,-3.579906,-2.590392), latitude=c(61.29000,52.73953,52.06530,50.43031,52.02951))
    point.ann_mean <- point_grid_extract(annual_mean,point_coord)
    point.month_sum <- point_grid_extract(monthly_sum,point_coord)
```

**5.** To extract long series, one chunk at a time (A quick and dirty workaround memory limit under Windows).

    # This is a workaround when facing memory issues under Windows while extracting a long series on a computer
    # with limited RAM.

```R
    library(climateExtract)

    climate_data <- extract_nc_value(1950, 1960, local_file=FALSE, clim_variable='mean temp', grid_size=0.25)
    point_coord <- data.frame(site_id = c("site1"), longitude = c(-1.3177988), latitude = c(51.7503954))

    annual_mean <- temporal_mean(climate_data, "annual")
    point.ann_mean <- point_grid_extract(annual_mean, point_coord)

    climate_data <- extract_nc_value(1961, 1970)
    annual_mean <- temporal_mean(climate_data, "annual")
    point.ann_mean <- rbind(point.ann_mean, point_grid_extract(annual_mean, point_coord))

    climate_data <- extract_nc_value(1971,1980)
    annual_mean <- temporal_mean(climate_data,"annual")
    point.ann_mean <- rbind(point.ann_mean,point_grid_extract(annual_mean,point_coord))

    climate_data <- extract_nc_value(1981, 1990)
    annual_mean <- temporal_mean(climate_data, "annual")
    point.ann_mean <- rbind(point.ann_mean, point_grid_extract(annual_mean, point_coord))

    climate_data <- extract_nc_value(1991, 2000)
    annual_mean <- temporal_mean(climate_data, "annual")
    point.ann_mean <- rbind(point.ann_mean, point_grid_extract(annual_mean, point_coord))

    climate_data <- extract_nc_value(2001, 2012)
    annual_mean <- temporal_mean(climate_data, "annual")
    point.ann_mean <- rbind(point.ann_mean, point_grid_extract(annual_mean, point_coord))


    names(point.ann_mean) <- c("year", "mean_temp") # I really need to fix this

    plot(point.ann_mean$year, point.ann_mean$mean_temp, type = 'l')
    abline(h = mean(point.ann_mean$mean_temp), col = 'red')
```

**6.** If you want a raster of the mean temperature across Europe for a specific year (e.g. 1988).

```R
    # get a raster

    library(climateExtract)
    library(raster)
    climate_data <- extract_nc_value(1988, 1988, local_file = FALSE, clim_variable = 'mean temp', grid_size = 0.25)

    # compute the annual mean temperature
    annual_mean <- temporal_mean(climate_data, "annual")

    # get a XY data.frame for the 0.25deg grid
    grid.e <- expand.grid(annual_mean$longitude, annual_mean$latitude)

    # extract the value for 1988 in one vector
    y1988 <- as.vector(annual_mean$value_array[ , , 1])

    # build a XYZ object
    xyz_value <- cbind(grid.e, y1988)

    # build a raster from the XYZ object with the library raster
    r <- rasterFromXYZ(xyz_value, crs = CRS("+init=epsg:4326"))
    names(r) <- annual_mean$date_extract[1]

    # voila!
    plot(r, main("Mean temperature in 1988")

    # you could use the stack() function to build a raster stack (multiple bands) with multiple years, months or days

```


>Note: This workflow, although it is still working should not be used on new application as newer options have been optimized